### ISSUE TITLE
decide on appropriate permissions management for member group representatives

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/legfed-django-site#2]
current model is basically "super or nothing". maybe that's OK but should be agreed to by the group.

**Comment by sammyjava** [comment]
Um I don't care about permissions. I say any admin has "super."

**Comment by adf-ncgr** [comment]
Does that imply you think everyone who gets a login should be an admin?

**Comment by sammyjava** [comment]
I don't see why not. Makes life simple.

**Comment by adf-ncgr** [comment]
OK with me as long as everyone else concerned is in consensus. NB: the last group discussion raised some questions concerning versioning of content that I was unable to answer (and have not subsequently researched). I believe we have established that the production site will be where content is added (no staging), so seems a reasonable thing to want to know. perhaps a separate issue, but I'm not going to start one.

**Comment by ekcannon** [comment]
I think we should be a little circumspect in handing out admin privileges. For example, a member database might assign update duties to a student. Suppose we make accounts edit-only unless the user requests super-user status and, unless it's obvious (e.g. it's Lacey or Stephen or Meg or ....) gives some rationale for needing the status.

I have a suspicion handling permissions will "just work" because we aren't likely to get too many requests, and may in fact have to beg people to sign up for accounts.

**Comment by sammyjava** [comment]
Exactly. _**We should be so lucky**_ as to have members assign students to update their stuff.

**Comment by adf-ncgr** [comment]
Group decision was for now to go with admin for anyone who needs to manage content and to make future decisions about policy (e.g. should group X be allowed to have a content manager?) by democratic consensus among the admins. We may revisit in future when we hit the student jackpot to which @sammyjava alludes.
